service: workshop

provider:
  name: aws
  runtime: nodejs4.3
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: "*"

functions:
  upload:
    handler: upload/index.upload
    events:
      - http:
          method: get
          path: upload
  list:
    handler: list/index.list
    events:
      - http:
          method: get
          path: list
  show:
    handler: show/index.show
    events:
      - http:
          method: get
          path: show
  resize:
    handler: resize/index.resize
    events:
      - s3:
          bucket: sconf-workshop-uploads
          event: s3:ObjectCreated:*
          rules:
            - prefix: image

resources:
  Resources:
    S3BucketSconfworkshopuploads:
      Properties:
        CorsConfiguration:
          CorsRules:
            - AllowedMethods:
                - PUT
              AllowedOrigins:
                - "*"
              AllowedHeaders:
                - "*"
