service: workshop

provider:
  name: aws
  runtime: nodejs4.3
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
        - kinesis:*
        - s3:*
      Resource: "*"

functions:
  upload:
    handler: upload/index.upload
    events:
      - http:
          method: get
          path: upload

resources:
  Resources:
    WorkshopTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: WorkshopUploadedImages
        AttributeDefinitions:
          - AttributeName: uuid
            AttributeType: S
        KeySchema:
          - AttributeName: uuid
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    WorkshopStream:
      Type: AWS::Kinesis::Stream
      Properties:
        Name: WorkshopVisits
        ShardCount: 1
    WorkshopBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: sconf-workshop-uploads # Provide custom name here
        CorsConfiguration:
          CorsRules:
            - AllowedMethods:
                - PUT
              AllowedOrigins:
                - "*"
              AllowedHeaders:
                - "*"
